### ISSUE TITLE
[DS105] Separate DS105M vs DS105L websites

### ISSUE THREAD

**Issue by jonjoncardoso** [LSE-DSI/lse-ds105-course-notes#121]
Here is what I have in mind: let's use the same github repo but replace the default home page for a home page where there are **two options:** "Click here for DS105M" vs "Click here for DS105L".

**Deadline:** Ideally, a PR by 11/01/2023 so we can amend details on Thursday and share with the new students on Friday.

**Tasks**

- [ ] Replace the home page by the idea above
- [ ] Move all of the current ds105 course pages to a sub-folder called "DS105M"
- [ ] Create a new subfolder called "DS105L"
- [ ] Build [DS101](https://github.com/LSE-DSI/lse-ds101-course-notes)'s webpage **locally** to understand how I have changed default colours (alternatively, study [Quarto's HTML theming](https://quarto.org/docs/output-formats/html-themes.html#custom-themes))
- [ ] Change DS105L main colour to #EE7600 or other type of orange (the key thing is that you should **feel** you are visiting a different website when you go from DS105M to DS105L
- [ ] Change DS105L main colour for the dark mode. (_I haven't searched for an alternative colour for that one, but dark mode is very popular among our students so it is very important to make it distinct from DS105M too_)

**Comment by jonjoncardoso** [comment]
@mc-o this will probably keep you busy for the entire week! Feel free to ask for clarification and for help throughout the week if anything is unclear.
