### ISSUE TITLE
[DS105] Create walkthrough for W02 - Part II

### ISSUE THREAD

**Issue by jonjoncardoso** [LSE-DSI/lse-ds105-course-notes#5]
- [ ] commands related to navigation (`pwd`, `cd`, ..)
- [ ] show the file system in Windows
- [ ] show the file system in Linux

**Comment by jonjoncardoso** [comment]
- [ ] Separate a few files to show as examples on the day of the lecture:
