### ISSUE TITLE
[DS105] - Create roadmap for W02 lab

### ISSUE THREAD

**Issue by jonjoncardoso** [LSE-DSI/lse-ds105-course-notes#6]
Students will work on exploring their own computers.

The roadmap, that explains what students must do during the lab, must involve:

- [x] commands related to navigation (pwd, cd, ..)
- [x] commands related to creation of files (touch, Emacs (?))
- [x] generic commands to search, print and move stuff around (cp, mv, cat, grep)
- [x] installation of something that involves setting environment variables

**Comment by jonjoncardoso** [comment]
Closed with a697a95f0b06077e07ac95025bdc01fcff51449e
