### ISSUE TITLE
[DS105] Create roadmap for W03 lab

### ISSUE THREAD

**Issue by jonjoncardoso** [LSE-DSI/lse-ds105-course-notes#7]
In the previous lab, students were introduced to The Terminal ([DS105 - W02 lab](https://lse-dsi.github.io/lse-ds105-course-notes/weeks/week02/lab.html)). Now, we want to teach them how to access a **remote computer instance on AWS**. 

We want students to really understand the fact that whatever commands they are running, they are doing it on a separate computer, different to their own. That's the main thing.

## Prep
- [x] Open a git branch from `develop` and name it `issue<number-of-this-issue>-<your-github-username>-roadmap-w03-lab`
- [x] Create a webpage for DS105 - W03 lab. This should have the same format as [DS105 - W02 lab](https://lse-dsi.github.io/lse-ds105-course-notes/weeks/week02/lab.html). You can check the source code [here](https://github.com/LSE-DSI/lse-ds105-course-notes/blob/main/weeks/week02/lab.qmd)
- [x] Read through the guides from last year [here](https://github.com/LSE-DSI/lse-ds105-course-notes/tree/main/weeks/week03/last%20year)
- [x] Get the AWS credentials from @jonjoncardoso (don't share credentials, passwords nor anything like that on Github)
- [ ] Replicate the setup (Admin guide) to make sure it is working

## Write the Lab roadmap

You can reuse whatever you feel is relevant from last year's lab roadmap.

Ensure you have included:
- [x] instructions to `ssh` to an EC2 instance 
- [x] instructions to navigate and create some files in the server
- [x] students should be able to realise they are inside another computer, with commands like `whoami`, `htop` or [others](https://www.thegeekstuff.com/2009/03/4-ways-to-identify-who-is-logged-in-on-your-linux-system/)
- [x] use `scp` to download files they created in the VM to their local machine
- [x] use `scp` to upload files they created in their local machine to the remove VM 

## Complete the task

- [x] Once you have finished, open a Pull Request from the git branch you created to `develop`. Tag @jonjoncardoso as a reviewer

**Comment by jonjoncardoso** [comment]
Chapter 4 of this textbook [A Hands-on Introduction to Data Science](https://www.cambridge.org/highereducation/books/a-hands-on-introduction-to-data-science/9D55C29C653872F13289EA7909953842) might be relevant
